### ISSUE TITLE
Is it possible to import html file?

### ISSUE THREAD

**Issue by noopole** [ModuleLoader/browser-es-module-loader#1]
With the library `system.js` I could import html files using:

`System.import( './template.html!text' ).then( ... )`

Is it/will it be possible to do the same with this library? 
Example:

```
<script type="module">
    import html as 'template.html'
</script>
```

I don't think it is a standard ES6 feature but it could be great substitute to HTML Imports.

**Comment by guybedford** [comment]
This feature isn't supported in this project.
