### ISSUE TITLE
'Promise' is undefined

### ISSUE THREAD

**Issue by inorganik** [ModuleLoader/browser-es-module-loader#10]
Hi, I have this implemented on a demo page of a js repo called CountUp: inorganik.github.io/countup.js

I believe I implemented as instructed, you can see the index.html file [here](https://github.com/inorganik/countUp.js/blob/master/index.html).

However in IE 11.379 it is is throwing
```
'Promise' is undefined'
``` 
on line 90 of browser-es-module-loader.js. I have also included babel-browser-build.js. Could you please take a look?

**Comment by inorganik** [comment]
Hi, is this still maintained? I notice the last commit was 3 years ago

**Comment by guybedford** [comment]
Hi @inorganik yes this project is no longer maintained since the loader specification is no longer on any standards track.

SystemJS would be the recommended alternative workflow - https://github.com/systemjs/systemjs#promises.
